export enum Getter {
  AVAILABLE_VEHICLES = 'AVAILABLE_VEHICLES',
  IS_LOADING = 'IS_LOADING',
  ERROR_MESSAGE = 'ERROR_MESSAGE',
  NOTIFICATION_MESSAGE = 'NOTIFICATION_MESSAGE',
  VEHICLE = 'VEHICLE'
}
